name: gleam_day
description: "Personal jewelry recommendation app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.0.0
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.3.3
  go_router: ^14.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: YujiMai
      fonts:
        - asset: assets/fonts/YujiMai-Regular.ttf
    - family: GowunBatang
      fonts:
        - asset: assets/fonts/GowunBatang-Bold.ttf
